# "service" is the name of this project. This will also be added to your AWS resource names.
service: authService
org: irenejoy21testapp
app: test-app  # Choose your app name

provider:
  name: aws
  runtime: nodejs24.x
  region: ap-southeast-2
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  signUp:
    handler: handlers/signUp.signUp
    events: 
      - httpApi:
          path: /sign-up
          method: post