# "service" is the name of this project. This will also be added to your AWS resource names.
service: authService
org: irenejoy21testapp
app: test-app  # Choose your app name

provider:
  name: aws
  runtime: nodejs24.x
  environment:
    CLIENT_ID: ${ssm:/CLIENT_ID}
    REGION: us-east-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:PutItem
      # STEP 2 NG ORDERS FRONT END
        - dynamodb:Query
      # END STEP 2
      Resource: 
        - arn:aws:dynamodb:us-east-1:660880134927:table/Users
        - arn:aws:dynamodb:us-east-1:660880134927:table/Users/index/EmailIndex
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S #string
          # STEP 2 NG ORDERS FRONT END
          - AttributeName: email
            AttributeType: S #string
          # END STEP 2
        KeySchema:
          - AttributeName: userId
            KeyType: HASH #partition key
        # STEP 2 NG ORDERS FRONT END
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        # END STEP 2
    # You can add AWS resources here, like DynamoDB tables, S3 buckets, etc.
    # Read the docs for more details: https://www.serverless.com/framework/docs/providers/aws/guide/resources
functions:
  signUp:
    handler: handlers/signUp.signUp
    events: 
      - httpApi:
          path: /sign-up
          method: post
  confirmSignUp:
    handler: handlers/confirmSignUp.confirmSignUp
    events:
      - httpApi:
          path: /confirm-sign-up
          method: post
  signIn:
    handler: handlers/signIn.signIn
    events:
      - httpApi:
          path: /sign-in
          method: post
  signOut:
    handler: handlers/signOut.signOut
    events:
      - httpApi:
          path: /sign-out
          method: post